### ISSUE TITLE
gulp-watch not working using Docker For Mac

### ISSUE THREAD

**Issue by makeaweli** [stonehippo/dockerfiles#1]
Running patternlab2 using dockerfiles/pattern-lab-2/node/gulp/Dockerfile with the following:

`docker run  -p 3000:3000 -v $(pwd)/patternlab/source:/opt/pattern-lab/source -v \
$(pwd)/zurb_foundation_gemini:/opt/pattern-lab/public/zurb_foundation_gemini  \
stonehippo/pattern-lab-2:node-gulp`

Any changes to shared volume on host won't trigger anything. However, logging into the container and touching any of the pattern lab source files will trigger gulp watch.

**Comment by makeaweli** [comment]
Looks like its just a Mac issue:
https://forums.docker.com/t/docker-compose-volumes-gulp-watch-100-cpu-usage/10192/14

**Comment by brunolm** [comment]
Also does not work on Docker for Windows.

To solve the issue for this and similar problems (`webpack-dev-middleware`, `nodemon`...) always look for a `polling` configuration.

In this case add to the config

```
usePolling: true
```
